In [5]:
import numpy as np

作業目標
讀取存取陣列資料
作業重點
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [6]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
# np.savez('two_array.npz',array1,array2)
with open('two_array.npz','wb') as f:
    np.savez(f,array1=array1,array2=array2)

In [7]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [23]:
load_array = np.load('two_array.npz')
array3 = np.array([[4,5,6],[1,2,3]])
with open('new_array.npz','wb') as f:
    np.savez(f,load_array ['array1'],load_array ['array2'],array3)
load_newarray = np.load('new_array.npz')

In [22]:
load_newarray.files

print(load_newarray['arr_0'])
print(load_newarray['arr_1'])
print(load_newarray['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
